version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - APP_NAME=${APP_NAME}
    command: >
      sh -c "
        uv pip install -r requirements.txt &&
        streamlit run main.py
      "
